# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'', verbose_name='Photo')),
                ('photo_thumbnail', models.ImageField(upload_to=b'', verbose_name='Photo Thumbnail')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sharoz_v1.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('size', models.CharField(max_length=10)),
                ('sex', models.CharField(default='F', max_length=10)),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('link_to_buy', models.TextField(blank=True, null=True, verbose_name='Link to buy')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sharoz_v1.Product'),
        ),
    ]
