# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharoz_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo Thumbnail'),
        ),
    ]
