# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharoz_v1', '0002_auto_20160426_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=500)),
            ],
        ),
    ]
