# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharoz_v1', '0003_suggest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggest',
        ),
    ]
